### ISSUE TITLE
Reset/Clear button on Database Explorer

### ISSUE THREAD

**Issue by sburggsx** [JAKAMI99/pwnamap#14]
The DB Explorer form needs a reset button.

**Comment by JAKAMI99** [comment]
Fixed

**Comment by JAKAMI99** [comment]
When testing on my own instance after pulling the latest docker, it didn't work at first. The button did just nothing.
Make sure to reload the website without using cache. On Firefox, it works trough one of these ways:

    Hold down the Shift key and left-click the Reload button
    Press "Ctrl + F5" or press "Ctrl + Shift + R" (Windows, Linux)
    Press "Command + Shift + R" (Mac)
