### ISSUE TITLE
Map Hover Over 

### ISSUE THREAD

**Issue by sburggsx** [JAKAMI99/pwnamap#15]
Would it be possible to have the AP data show as a hover on the pwnamap?

**Comment by JAKAMI99** [comment]
Why would you prefer a hover over a click? Not sure why somebody would want that, but maybe I am wrong?

**Comment by sburggsx** [comment]
When looking at the map, you can go from AP to AP and see the basic info. If you're looking for a specific one, if you have to click in and out on every one it would be time consuming. 

The hover would be for fast identification or searching.

**Comment by JAKAMI99** [comment]
What about only showing the Name of the network?
A whole on Hover with all information would be kinda bulky

**Comment by JAKAMI99** [comment]
I added a popup just for mouse hovering which shows the name of the network.
Can you test it?
Feel free to get back, if you have feedback

**Comment by sburggsx** [comment]
Yes, that's great. The only other thing I would consider adding to it would be the capture date/time.... maybe. Let me use this for a bit first.
